tasks:
  - name: Install AWS CLI on Linux
    init: |
      # Update package lists and install prerequisites
      sudo apt update
      sudo apt install -y unzip curl
      
      # Download and install the AWS CLI for Linux
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      # Verify installation
      aws --version

      # Clean up installation files
      rm -rf aws awscliv2.zip

