# tasks:
#   # - name: Install python
#   #   command: |
#   #     sudo apt-get update
#   #     sudo apt-get install -y python3 python3-pip python3.10-venv
#   - name: Create Python symlink
#     command: |
#       sudo ln -s /usr/bin/python3 /usr/bin/python
#   - name: aws-cli
#     env:
#       AWS_CLI_AUTO_PROMPT: on-partial
#     before: |
#       cd /workspace
#       curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
#       unzip awscli-bundle.zip
#       sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
#       cd $THEIA_WORKSPACE_ROOT
tasks:
  - name: Install AWS CLI on Linux
    init: |
      # Update package lists and install prerequisites
      sudo apt update
      sudo apt install -y unzip curl
      
      # Download and install the AWS CLI for Linux
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install

      # Verify installation
      aws --version

      # Clean up installation files
      rm -rf aws awscliv2.zip

